<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OxDb.ServerGame\OxDb.ServerGame.csproj" />
    <ProjectReference Include="..\..\OxDb.SharedPlatform\OxDb.SharedPlatform.csproj" />
  </ItemGroup>

</Project>
