using Genrpg.Shared.Interfaces;
using Genrpg.Shared.Serialization.Attributes;
using MessagePack;

namespace Genrpg.Shared.DataStores.Categories.PlayerData.Units
{
    [MessagePackInterface]

    [Union(0 ,typeof(Genrpg.Shared.UserMail.PlayerData.UserLetter))]
    [Union(1 ,typeof(Genrpg.Shared.UserMail.PlayerData.UserMailData))]
    [Union(2 ,typeof(Genrpg.Shared.UserMail.PlayerData.UserMailDto))]
    [Union(3 ,typeof(Genrpg.Shared.Spells.PlayerData.CombatAbilityRank))]
    [Union(4 ,typeof(Genrpg.Shared.Spells.PlayerData.CombatAbilityData))]
    [Union(5 ,typeof(Genrpg.Shared.Spells.PlayerData.CombatAbilityDto))]
    [Union(6 ,typeof(Genrpg.Shared.Spells.PlayerData.Spells.Spell))]
    [Union(7 ,typeof(Genrpg.Shared.Spells.PlayerData.Spells.SpellData))]
    [Union(8 ,typeof(Genrpg.Shared.Spells.PlayerData.Spells.SpellDto))]
    [Union(9 ,typeof(Genrpg.Shared.Quests.PlayerData.QuestStatus))]
    [Union(10 ,typeof(Genrpg.Shared.Quests.PlayerData.QuestData))]
    [Union(11 ,typeof(Genrpg.Shared.Quests.PlayerData.QuestDto))]
    [Union(12 ,typeof(Genrpg.Shared.Purchasing.PlayerData.CompletedPurchaseData))]
    [Union(13 ,typeof(Genrpg.Shared.Purchasing.PlayerData.CurrentPurchaseData))]
    [Union(14 ,typeof(Genrpg.Shared.Purchasing.PlayerData.PlayerStoreOfferData))]
    [Union(15 ,typeof(Genrpg.Shared.Purchasing.PlayerData.PlayerStoreOfferDto))]
    [Union(16 ,typeof(Genrpg.Shared.Purchasing.PlayerData.PurchaseHistoryDto))]
    [Union(17 ,typeof(Genrpg.Shared.Purchasing.PlayerData.PurchaseHistoryData))]
    [Union(18 ,typeof(Genrpg.Shared.Trader.Stats.PlayerData.TraderStatData))]
    [Union(19 ,typeof(Genrpg.Shared.Trader.Stats.PlayerData.TraderStatDto))]
    [Union(20 ,typeof(Genrpg.Shared.Trader.Holdings.PlayerData.HoldingsData))]
    [Union(21 ,typeof(Genrpg.Shared.Trader.Holdings.PlayerData.HoldingsDto))]
    [Union(22 ,typeof(Genrpg.Shared.Trader.Caravans.PlayerData.CaravanData))]
    [Union(23 ,typeof(Genrpg.Shared.Trader.Caravans.PlayerData.CaravanDto))]
    [Union(24 ,typeof(Genrpg.Shared.LoadSave.PlayerData.SaveSlotData))]
    [Union(25 ,typeof(Genrpg.Shared.Inventory.PlayerData.InventoryData))]
    [Union(26 ,typeof(Genrpg.Shared.Inventory.PlayerData.InventoryDto))]
    [Union(27 ,typeof(Genrpg.Shared.Inventory.PlayerData.Item))]
    [Union(28 ,typeof(Genrpg.Shared.Input.PlayerData.ActionInput))]
    [Union(29 ,typeof(Genrpg.Shared.Input.PlayerData.ActionInputData))]
    [Union(30 ,typeof(Genrpg.Shared.Input.PlayerData.ActionInputDto))]
    [Union(31 ,typeof(Genrpg.Shared.Input.PlayerData.KeyComm))]
    [Union(32 ,typeof(Genrpg.Shared.Input.PlayerData.KeyCommData))]
    [Union(33 ,typeof(Genrpg.Shared.Input.PlayerData.KeyCommDto))]
    [Union(34 ,typeof(Genrpg.Shared.Ftue.PlayerData.FtueData))]
    [Union(35 ,typeof(Genrpg.Shared.Ftue.PlayerData.FtueDto))]
    [Union(36 ,typeof(Genrpg.Shared.Factions.PlayerData.ReputationStatus))]
    [Union(37 ,typeof(Genrpg.Shared.Factions.PlayerData.ReputationData))]
    [Union(38 ,typeof(Genrpg.Shared.Factions.PlayerData.ReputationDto))]
    [Union(39 ,typeof(Genrpg.Shared.Currencies.PlayerData.CurrencyData))]
    [Union(40 ,typeof(Genrpg.Shared.Currencies.PlayerData.CurrencyStatus))]
    [Union(41 ,typeof(Genrpg.Shared.Currencies.PlayerData.CurrencyDto))]
    [Union(42 ,typeof(Genrpg.Shared.Crawler.Parties.PlayerData.PartyDto))]
    [Union(43 ,typeof(Genrpg.Shared.Crafting.PlayerData.Recipes.RecipeStatus))]
    [Union(44 ,typeof(Genrpg.Shared.Crafting.PlayerData.Recipes.RecipeData))]
    [Union(45 ,typeof(Genrpg.Shared.Crafting.PlayerData.Recipes.RecipeDataDto))]
    [Union(46 ,typeof(Genrpg.Shared.Crafting.PlayerData.Crafting.CraftingStatus))]
    [Union(47 ,typeof(Genrpg.Shared.Crafting.PlayerData.Crafting.CraftingData))]
    [Union(48 ,typeof(Genrpg.Shared.Crafting.PlayerData.Crafting.CraftingDto))]
    [Union(49 ,typeof(Genrpg.Shared.Core.PlayerData.CoreData))]
    [Union(50 ,typeof(Genrpg.Shared.Core.PlayerData.CoreDataDto))]
    [Union(51 ,typeof(Genrpg.Shared.Core.PlayerData.GameAccount))]
    [Union(52 ,typeof(Genrpg.Shared.Chests.PlayerData.ChestData))]
    [Union(53 ,typeof(Genrpg.Shared.Chests.PlayerData.ChestStatus))]
    [Union(54 ,typeof(Genrpg.Shared.Chests.PlayerData.ChestDto))]
    [Union(55 ,typeof(Genrpg.Shared.Charms.PlayerData.PlayerCharm))]
    [Union(56 ,typeof(Genrpg.Shared.Charms.PlayerData.PlayerCharmData))]
    [Union(57 ,typeof(Genrpg.Shared.Charms.PlayerData.PlayerCharmDto))]
    [Union(58 ,typeof(Genrpg.Shared.CharMail.PlayerData.CharLetter))]
    [Union(59 ,typeof(Genrpg.Shared.CharMail.PlayerData.CharMailData))]
    [Union(60 ,typeof(Genrpg.Shared.CharMail.PlayerData.CharMailDto))]
    [Union(61 ,typeof(Genrpg.Shared.Characters.PlayerData.CoreCharacter))]
    [Union(62 ,typeof(Genrpg.Shared.Achievements.PlayerData.AchievementData))]
    [Union(63 ,typeof(Genrpg.Shared.Achievements.PlayerData.AchievementStatus))]
    [Union(64 ,typeof(Genrpg.Shared.Achievements.PlayerData.AchievementDto))]
    public interface IUnitData : IStringId
    {
        IUnitData Unpack();
    }
}


